name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: pedropregnolato
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
window.snake.flag({
  primary: [ // the flag for the used-to-be-rainbow snake
    '#rrggbb', // hex code, the first color
    '#rrggbb', // hex code, the second color
    '#rrggbb', // hex code, the third color
  ], // you can have as many colors as you want in here, it can be fewer or more than three
  yinYang: [ // the flag for the second snake in yinyang mode
    '#rrggbb', // hex code, the first color
    '#rrggbb', // hex code, the second color
    '#rrggbb', // hex code, the third color
  ], // you can have as many colors as you want in here, it can be fewer or more than three
}); 
